### ISSUE TITLE
Rename VSTeam to e.g. ADOPS?

### ISSUE THREAD

**Issue by MichelZ** [DarqueWarrior/vsteam#138]
"VSTeam" is IMHO not a good name anymore, now that everything has been renamed away from that brand.

Does it make sense to rename the project to something like "ADOPS" and all cmdlets to Get-ADO* / Set-ADO* etc. ?

**Comment by MichelZ** [comment]
I see you use "AzD" as short for Azure DevOps. Is this the official term? "VSTS" was so catchy :D

**Comment by DarqueWarrior** [comment]
There is no official abbreviation. ADO already means something else in our industry. I have considered renaming the module but I don't think I will try and align with the product anymore. Have to think of a cool name not associated with the product name. I hesitate because renaming also means losing the download stats.
