### ISSUE TITLE
[Feature] Add powershell support to download universal packages from Azure DevOps

### ISSUE THREAD

**Issue by alesgn** [DarqueWarrior/vsteam#151]
At the moment, since Universal Packages in Azure DevOps are still in Public Preview, it is possible to download them only using the azure-cli or alternatively via vsts-cli.
It would be very useful to have the possibility to pull Universal Packages using just powershell without the need to install a client to do it.

**Comment by SebastianSchuetze** [comment]
I have checked the API and there is currently now way of getting it with that. The azure CLI is also using an extra internal CLI to authenticate through the Azure Portal an request an SAS token on an intenal storage account hosted with Azure DevOps

I checked it with fiddle and the azure CLI

![image](https://user-images.githubusercontent.com/7256168/75902032-b6bcd280-5e3f-11ea-95d0-e91fe5437964.png)

So unless there is an API which returns the blob URL + SAS token, we will not be able to implement this at all @alesgn

**Comment by SebastianSchuetze** [comment]
This seems not to be possible as mentioned here:
https://github.com/MicrosoftDocs/azure-devops-docs/issues/3834

There is a feature request for supporting this with the API:
https://developercommunity.visualstudio.com/idea/616820/download-universal-package-rest-api.html

It is also stated in the documentation that you have to use the Azure CLI currently:
> You must use the Azure CLI to download the package. Azure DevOps doesn't support direct HTTP/HTTPS download links or other ways to download the package.

https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops&tabs=azuredevops#download-a-universal-package

@alesgn please support the feature request. Otherwise, we cannot do anything to implement it. I will close this for now. You can reopen it if you see a possibility to still implement it.
