### ISSUE TITLE
Changing the Process Model

### ISSUE THREAD

**Issue by InteXX** [DarqueWarrior/vsteam#195]
Will this tool assist in migrating data between collections with disparate process models?

In other words, I'd like to switch from XML to Inheritance.

**Comment by DarqueWarrior** [comment]
Sorry for the delay. I am not sure I understand the question.

**Comment by DarqueWarrior** [comment]
I see.  I have not tried that use case. @SebastianSchuetze has spent a lot more time with the work item API. He might have some idea of what is possible.

**Comment by SebastianSchuetze** [comment]
@InteXX from what I see, the work item cmdlets can potentially get work items and can create new work items. But unfortunately, they do not get the history currently.

Also, there is no way currently to get the history easily.

What is connected to the work item are also the following things:

- keep attachments?
- keep comments (also their versions, since comments can be edited)?
- keep that all dates of the history (when was something edited) or only the values?
- keep links and also restore links to the migrated work items?
- try to find the new identities? What should happen if the identity is not found?

Those are the first things that come into my mind. I am not even sure how to copy history. There is only a possibility to [get all revisions](https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/revisions?view=azure-devops-rest-5.1) but not how to update them. I would currently guess that you have to create the work item from the first revision and then simulate the history by sequentially updating the new work item with the history of the old.

so the question is now how detailed the migration must be.

**Comment by InteXX** [comment]
@SebastianSchuetze 

> so the question is now how detailed the migration must be

Well... pretty much everything. I'd like to see everything that's in the project on the old collection migrated to the new.

**Comment by SebastianSchuetze** [comment]
Currently, I can say that is not possible. There is also nothing implemented that event exports the history of an item. Maybe in the future, it will be possible, but you are free to contribute to that goal if you want. ;-)

**Comment by InteXX** [comment]
Very good, thank you.
