### ISSUE TITLE
Trouble with some Aliases

### ISSUE THREAD

**Issue by BastienPerdriau** [DarqueWarrior/vsteam#85]
Hi,
I just installed the module and I noticed some Aliases which are still with the "VSTeam" part in their name.
I don't know if it's normal or not so I ask you directly.

Here are the aliases : 
- Add-VSTeamReleaseEnvironment
- Remove-VSTeamAzureRMServiceEndpoint
- Remove-VSTeamServiceFabricEndpoint
- Remove-VSTeamSonarQubeEndpoint

Of course, these aliases are not in the function set when I enter my "Get-Command -Module VSTeam" command.
It's not a real big deal, and if you want, I can send you a PR to fix it.

**Comment by DarqueWarrior** [comment]
Thanks for checking first because all these are on purpose.  But I should provide better comments in the code.

Add-VSTeamReleaseEnvironment was to avoid a breaking change. I renamed a function from Add-VSTeamReleaseEnvironment to Set-VSTeamEnvironmentStatus and the alias avoided breaking those using the old name. 

The Remove-VSTeamXXXEndpoint all map to Remove-VSTeamSerivceEndpoint to improve discoverability. Because there is an Add-VSTeamXXXEndpoint I felt there should be a matching Remove even though they all map to Remove-VSTeamServiceEndpoint. 

Thanks for pointing out this confusion and I will document the code.

**Comment by DarqueWarrior** [comment]
Comments added and pushed to master. Thanks again.
