### ISSUE TITLE
Update-VSTeamUser may not be able to validate a user per email when user count is greater than 100

### ISSUE THREAD

**Issue by GPugnet** [DarqueWarrior/vsteam#90]
Update-VSTeamUser validates that the user submitted by email exists using the following code :

`         $user = Get-VSTeamUser | Where-Object email -eq $email`

As Get-VSTeamUser only returns the top 100 users, the user to be validated may not be found.

**Comment by DarqueWarrior** [comment]
The best we can do if the user wants to use email is pass in the max top of 10,000. However, this feels very inefficient. If you have that many users you would be better off finding the ID using Get-VSTeamUser yourself first. Then calling Update-VSTeamUser by ID instead of by Email. The filter only lets you filter by extensionId today which does not help in this situation. If at some point they add user.principalName or user.mailAddress we can update this code. 

For now, I will pass in the Max Top of 10,000. I will also update the help to explain the costs.

**Comment by DarqueWarrior** [comment]
Fixed in PR [96](https://github.com/DarqueWarrior/vsteam/pull/96)
